components:
  schemas:
    Colecionador:
      type: object
      properties:
        id:
          type: integer
        nome:
          type: string
        email:
          type: string
        perfil:
          type: string
          enum: [COLECIONADOR, ADMINISTRADOR]

    Item:
      type: object
      properties:
        id:
          type: integer
        titulo:
          type: string
        descricao:
          type: string
        fotoUrl:
          type: string
        estadoConservacao:
          type: string
          enum: [Novo, Excelente, Marcas de Uso, Danificado]
        raridade:
          type: string
          enum: [Comum, Raro, Épico, Lendário]
        colecionadorId:
          type: integer

    PropostaTroca:
      type: object
      properties:
        id:
          type: integer
        solicitanteId:
          type: integer
        destinatarioId:
          type: integer
        itensSolicitanteIds:
          type: array
          items:
            type: integer
        itensDestinatarioIds:
          type: array
          items:
            type: integer
        status:
          type: string
          enum: [PENDENTE, ACEITA, RECUSADA]